export interface CompanyToList {
    comp_amount: string;
    comp_area: string;
    comp_banno: string;
    comp_business: string;
    comp_contact: string;
    comp_createdate: string;
    comp_desc: string;
    comp_employee: string;
    comp_extra_url: string;
    comp_fax: string;
    id: string;
    comp_industry: string;
    comp_location: string;
    comp_media_report: string;
    comp_name: string;
    comp_tag: string;
    comp_tel: string;
    comp_url: string;
    done: string;
    confirmed: number;
    comp_keyword: string;
    extra: string;
    representative: string;
    approved_date: string;
    capital: number;
    location: string;
    established_date: string;
}